version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: 'pub'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '00:00'
      timezone: 'Asia/Tokyo'
    # open-pull-requests-limit: 10
    versioning-strategy: increase
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '00:00'
      timezone: 'Asia/Tokyo'
    open-pull-requests-limit: 10
    groups:
      dependencies:
        patterns:
          - '*'
