version: 2
updates:
  - package-ecosystem: 'pub'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '00:00'
      timezone: 'Asia/Tokyo'
    open-pull-requests-limit: 10
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '00:00'
      timezone: 'Asia/Tokyo'
    open-pull-requests-limit: 10
