version: 2
enable-beta-ecosystems: true
updates:
  # Maintain dependencies for pub.dev
  - package-ecosystem: 'pub'
    directory: '/'
    schedule:
      interval: 'daily'
      time: "00:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 10
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
      time: "00:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 10
