include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    sort_pub_dependencies: false
    public_member_api_docs: false
    flutter_style_todos: false
    lines_longer_than_80_chars: false
analyzer:
  exclude:
    - '**/*.g.dart'
  plugins:
    - custom_lint
