targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - implicit_dynamic_parameter
            - implicit_dynamic_type
            - implicit_dynamic_method
            - strict_raw_type
      slang_build_runner:
        options:
          input_directory: lib/i18n
      # drift_dev:
      #   options:
      #     sql:
      #       dialect: sqlite
      #       options:
      #         modules:
      #           - json1
      #           - fts5
      #           - math
