targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - implicit_dynamic_parameter
            - implicit_dynamic_type
            - implicit_dynamic_method
            - strict_raw_type
      slang_build_runner:
        options:
          input_directory: lib/i18n
          input_file_pattern: .i18n.yaml
