name: buzz_recipe_viewer
description: A new Flutter project.

publish_to: 'none'

version: 2.2.0+140

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_dotenv: ^5.2.1
  intl: ^0.19.0
  url_launcher: ^6.3.1
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  path_provider: ^2.1.5
  youtube_player_flutter: ^9.1.1
  settings_ui: ^2.0.2
  package_info_plus: ^8.1.1
  shared_preferences: ^2.3.3
  custom_text: ^2.0.2
  like_button: ^2.0.5
  collection: ^1.18.0
  slang: ^4.2.1
  slang_flutter: ^4.2.0
  mockito: ^5.4.4
  path: ^1.9.0
  introduction_screen: ^3.1.14
  flutter_inappwebview: ^6.1.5
  in_app_review: ^2.0.10
  app_settings: ^5.1.1
  go_router: ^14.6.1

  firebase_core: ^3.4.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.6
  firebase_messaging: ^15.1.5
  firebase_analytics: ^11.3.5
  firebase_remote_config: ^5.1.5
  firebase_in_app_messaging: ^0.8.0
  firebase_app_installations: ^0.3.1

  flutter_use: ^0.0.4
  algoliasearch: ^1.24.0
  algolia_helper_flutter: ^1.1.0
  image_picker: ^1.1.2
  uuid: ^4.5.1
  cross_file: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  cider: ^0.2.8
  freezed: ^2.5.7
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  very_good_analysis: ^6.0.0
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
  custom_lint: ^0.7.0
  flutter_launcher_icons: ^0.14.1
  slang_build_runner: ^4.2.0
  golden_toolkit: ^0.15.0
  flutter_gen_runner: ^5.8.0

dependency_overrides:
  algolia_client_core: 1.27.1
  algolia_client_insights: 1.27.1
  algolia_client_search: 1.27.1
  algoliasearch: 1.27.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: fonts/NotoSansJP-Regular.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
