name: buzz_recipe_viewer
description: A new Flutter project.

publish_to: 'none'

version: 2.0.3+121

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: any
  freezed_annotation: any
  json_annotation: any
  algolia: any
  flutter_dotenv: any
  intl: any
  url_launcher: any
  flutter_hooks: any
  hooks_riverpod: any
  riverpod_annotation: any
  path_provider: any
  youtube_player_flutter: ^9.0.0
  settings_ui: any
  package_info_plus: any
  shared_preferences: any
  custom_text: any
  like_button: any
  collection: any
  flutter_localizations:
    sdk: flutter
  slang: any
  slang_flutter: any
  mockito: any
  drift: any
  sqlite3_flutter_libs: any
  path: any
  sqlite3: any
  introduction_screen: any
  flutter_inappwebview: any
  in_app_review: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  cider: any
  freezed: any
  build_runner: any
  json_serializable: any
  very_good_analysis: any
  riverpod_generator: any
  riverpod_lint: any
  custom_lint: any
  flutter_launcher_icons: any
  slang_build_runner: any
  golden_toolkit: any
  drift_dev: any
  flutter_gen_runner: any

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: fonts/NotoSansJP-Regular.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
