name: buzz_recipe_viewer
description: A new Flutter project.

publish_to: 'none'

version: 2.1.0+129

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  algolia: ^1.1.2
  flutter_dotenv: ^5.1.0
  intl: ^0.19.0
  url_launcher: ^6.3.0
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.2
  riverpod_annotation: ^2.3.5
  path_provider: ^2.1.4
  youtube_player_flutter: ^9.0.3
  settings_ui: ^2.0.2
  package_info_plus: ^8.0.2
  shared_preferences: ^2.3.2
  custom_text: ^2.0.2
  like_button: ^2.0.5
  collection: ^1.18.0
  slang: ^3.31.2
  slang_flutter: ^3.31.0
  mockito: ^5.4.4
  drift: ^2.19.1+1
  sqlite3_flutter_libs: ^0.5.24
  path: ^1.9.0
  sqlite3: ^2.4.5
  introduction_screen: ^3.1.14
  flutter_inappwebview: ^6.0.0
  in_app_review: ^2.0.9
  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.0
  app_settings: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  cider: ^0.2.8
  freezed: ^2.5.7
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  very_good_analysis: ^6.0.0
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13
  custom_lint: ^0.6.5
  flutter_launcher_icons: ^0.13.1
  slang_build_runner: ^3.31.0
  golden_toolkit: ^0.15.0
  drift_dev: ^2.19.1
  flutter_gen_runner: ^5.7.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: fonts/NotoSansJP-Regular.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
