name: buzz_recipe_viewer
description: A new Flutter project.

publish_to: 'none'

version: 2.0.0+107

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: any
  freezed_annotation: any
  json_annotation: ^4.8.1
  algolia: any
  flutter_dotenv: any
  intl: any
  url_launcher: any
  flutter_hooks: any
  hooks_riverpod: any
  riverpod_annotation: any
  path_provider: any
  youtube_player_flutter: ^9.0.0
  settings_ui: any
  package_info_plus: any
  shared_preferences: any
  custom_text: any
  like_button: any
  collection: any
  flutter_localizations:
    sdk: flutter
  slang: any
  slang_flutter: any
  mockito: any
  drift: any
  sqlite3_flutter_libs: any
  path: any
  sqlite3: any
  introduction_screen: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  cider: any
  freezed: any
  build_runner: any
  json_serializable: any
  very_good_analysis: any
  riverpod_generator: any
  riverpod_lint: any
  custom_lint: any
  flutter_launcher_icons: any
  slang_build_runner: any
  golden_toolkit: any
  drift_dev: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: fonts/NotoSansJP-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
