name: Setup Flutter
description: Setup Flutter
inputs:
  version:
    description: Flutter version
runs:
  using: composite
  steps:
    - name: Set path and env
      shell: bash
      run: |
        echo "${{ runner.temp }}/flutter/bin" >> $GITHUB_PATH
        echo "${{ runner.temp }}/flutter/.pub-cache/bin" >> $GITHUB_PATH
        echo "PUB_CACHE=${{ runner.temp }}/flutter/.pub-cache" >> $GITHUB_ENV

    - name: Install Flutter
      shell: bash
      env:
        FLUTTER_PATH: ${{ runner.temp }}/flutter
      run: |
        git clone https://github.com/flutter/flutter.git --depth 1 --branch ${{ inputs.version }} ${{ env.FLUTTER_PATH }}
        cd ${{ env.FLUTTER_PATH }} $$ pwd
        cd ${{ env.FLUTTER_PATH }} $$ git rev-parse HEAD
        cd ${{ env.FLUTTER_PATH }} $$ echo "FLUTTER_HASH=`git rev-parse HEAD`" >> $GITHUB_ENV

    - name: Cache
      uses: actions/cache@v3
      env:
        FLUTTER_PATH: ${{ runner.temp }}/flutter
      with:
        path: |
          ${{ env.FLUTTER_PATH }}/bin/cache
          ${{ env.FLUTTER_PATH }}/.pub-cache
        key: flutter-setup-cache-${{ runner.os }}-${{ runner.arch }}-${{ inputs.version }}-${{ env.FLUTTER_HASH }}-${{ hashFiles('pubspec.lock') }}

    - shell: bash
      run: flutter --version

    - shell: bash
      run: flutter pub get
