name: Setup Flutter
description: Setup Flutter
inputs:
  version:
    description: Flutter version
runs:
  using: composite
  steps:
    - name: Set path and env
      shell: bash
      run: |
        echo "FLUTTER_ROOT=${{ runner.temp }}/flutter" >> $GITHUB_ENV
        echo "PUB_CACHE=${{ runner.temp }}/flutter/.pub-cache" >> $GITHUB_ENV
        echo "${{ runner.temp }}/flutter/bin" >> $GITHUB_PATH
        echo "${{ runner.temp }}/flutter/bin/cache/dart-sdk/bin" >> $GITHUB_PATH
        echo "${{ runner.temp }}/flutter/.pub-cache/bin" >> $GITHUB_PATH

    - name: Install Flutter
      shell: bash
      run: |
        git clone https://github.com/flutter/flutter.git --depth 1 --branch ${{ inputs.version }} ${{ env.FLUTTER_ROOT }}
        echo "FLUTTER_GIT_HASH=`cd ${{ env.FLUTTER_ROOT }} && git rev-parse HEAD`" >> $GITHUB_ENV

    - name: Cache
      uses: actions/cache@v3
      with:
        path: |
          ${{ env.FLUTTER_ROOT }}/bin/cache
          ${{ env.FLUTTER_ROOT }}/.pub-cache
        key: flutter-setup-cache-${{ runner.os }}-${{ runner.arch }}-${{ inputs.version }}-${{ env.FLUTTER_GIT_HASH }}-${{ hashFiles('pubspec.lock') }}

    - shell: bash
      run: flutter --version

    - shell: bash
      run: flutter pub get
