name: 02 bump pull request

run-name: Bump with Pull Request ${{ (vars.RUNS_ON_SELF_HOSTED == null && '(on GitHub-hosted)') || '(on self-hosted)' }}

on:
  workflow_dispatch:
    inputs:
      bump:
        type: choice
        description: Bump Target
        options:
          - build
          - patch
          - minor
          - major

env:
  GIT_USER_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
  GIT_USER_NAME: "github-actions[bot]"

permissions:
  contents: write
  pull-requests: write

jobs:
  bump:
    runs-on: ${{ (vars.RUNS_ON_SELF_HOSTED == null && 'ubuntu-latest') || 'self-hosted' }}
    timeout-minutes: 30
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ (vars.FLUTTER_VERSION != null && vars.FLUTTER_VERSION) || '' }}
          channel: stable
          cache: ${{ (vars.RUNS_ON_SELF_HOSTED == null && true) || false }}

      - run: flutter pub get

      - name: init git config
        run: |
          git config --local user.name $GIT_USER_NAME
          git config --local user.email $GIT_USER_EMAIL

      - name: bump up version
        run: |
          echo choice: ${{ github.event.inputs.bump }}
          flutter pub run cider bump ${{ github.event.inputs.bump }} --bump-build
          echo "BUMP_VERSION=$(flutter pub run cider version)" >> $GITHUB_ENV

      - name: commit pubspec.yaml
        run: |
          git add -u pubspec.yaml
          echo "Bumped version: $BUMP_VERSION" | git commit --file=-

      - name: create release branch
        run: |
          git checkout -b releases/$BUMP_VERSION
          echo "RELEASE_BRANCH=releases/$BUMP_VERSION" >> $GITHUB_ENV

      - name: push branch
        run: |
          git push -u origin $RELEASE_BRANCH

      - name: create pull request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --base ${{ github.ref_name }} --head $RELEASE_BRANCH --title "Release $BUMP_VERSION" --body "Release $BUMP_VERSION"
