name: Workflow for check

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
  workflow_dispatch:

jobs:
  analyze:
    uses: ./.github/workflows/analyze.job.yaml
    secrets: inherit
  test:
    uses: ./.github/workflows/test.job.yaml
    secrets: inherit
