name: 06 Deliver for GitHub Pages

run-name: Deliver for GitHub Pages ${{ (vars.RUNS_ON_SELF_HOSTED == null && '(on GitHub-hosted)') || '(on self-hosted)' }}

on:
  workflow_dispatch:
    inputs:
      upload:
        description: 'Upload'
        type: boolean
        default: true
  workflow_call:
    inputs:
      upload:
        description: 'Upload'
        type: boolean
        default: true

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  deploy-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - uses: actions/configure-pages@v5

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ (vars.FLUTTER_VERSION != null && vars.FLUTTER_VERSION) || '' }}
          channel: stable
          cache: ${{ (vars.RUNS_ON_SELF_HOSTED == null && true) || false }}

      - run: |
          make build-runner 
          flutter pub get
          flutter build web --dart-define=FLAVOR=dev

      - name: Upload artifact
        if: ${{ inputs.upload }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

      - name: Deploy to GitHub Pages
        if: ${{ inputs.upload }}
        id: deployment
        uses: actions/deploy-pages@v4

  action-timeline:
    needs: [deploy-pages]
    if: ${{ !cancelled() && github.event.workflow == '.github/workflows/deliver-pages.yml' }}
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: Kesin11/actions-timeline@v2
