name: 03 Deliver for staging

run-name: Deliver for staging ${{ (vars.RUNS_ON_SELF_HOSTED == null && '(on GitHub-hosted)') || '(on self-hosted)' }}

on:
  workflow_dispatch:
    inputs:
      upload:
        description: 'Upload'
        type: boolean
        default: true
  workflow_call:
    inputs:
      upload:
        description: 'Upload'
        type: boolean
        default: true

env:
  DEVELOPER_DIR: ${{ (vars.DEVELOPER_DIR == null && '/Applications/Xcode_16.2.app') || vars.DEVELOPER_DIR }}

defaults:
  run:
    shell: bash -euo pipefail {0}

jobs:
  android:
    runs-on: ${{ (vars.RUNS_ON_SELF_HOSTED == null && 'ubuntu-24.04') || 'self-hosted' }}
    environment: staging
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Run pre-process script
        shell: bash
        env:
          PREPROCESS_SCRIPT_BASE64: ${{ secrets.PREPROCESS_SCRIPT_BASE64 }}
        run: |
          if [ -n "$PREPROCESS_SCRIPT_BASE64" ]; then
            echo "$PREPROCESS_SCRIPT_BASE64" | base64 --decode > ${{ runner.temp }}/pre-process.sh && bash ${{ runner.temp }}/pre-process.sh
          fi

      - uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: |
            /usr/local/lib/android/sdk/platforms/android-31
            /usr/local/lib/android/sdk/platforms/android-33
            /usr/local/lib/android/sdk/cmake/3.22.1
          key: android-sdk-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/build.gradle') }}

      - uses: subosito/flutter-action@e938fdf56512cc96ef2f93601a5a40bde3801046 # v2.19.0
        with:
          flutter-version: ${{ (vars.FLUTTER_VERSION != null && vars.FLUTTER_VERSION) || '' }}
          channel: stable
          cache: ${{ (vars.RUNS_ON_SELF_HOSTED == null && true) || false }}

      - run: flutter pub get

      - name: flutterfire configure
        env:
          FIREBASE_SERVICE_ACCOUNT_JSON_BASE64: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON_BASE64 }}
        run: |
          which firebase || curl -sL https://firebase.tools | analytics=false bash
          firebase --version
          which flutterfire || dart pub global activate flutterfire_cli
          flutterfire -v
          echo -n "$FIREBASE_SERVICE_ACCOUNT_JSON_BASE64" | base64 --decode > ${{ runner.temp }}/firebase_service_account.json
          GOOGLE_APPLICATION_CREDENTIALS=${{ runner.temp }}/firebase_service_account.json make flutterfire-configure-stg

      - name: Extract key.properties file
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          ANDROID_KEY_PROPERTIES_BASE64: ${{ secrets.ANDROID_KEY_PROPERTIES_BASE64 }}
        run: |
          echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > ${{ runner.temp }}/release.jks
          echo "$ANDROID_KEY_PROPERTIES_BASE64" | base64 --decode > android/key.properties
          echo storeFile=${{ runner.temp }}/release.jks >> android/key.properties

      - name: Build app bundle
        run: flutter build apk --dart-define=FLAVOR=stg

      - name: Extract Firebase App Distribution Service Account file
        if: ${{ inputs.upload }}
        env:
          FIREBASE_APP_DISTRIBUTION_SERVICE_ACCOUNT_JSON_BASE64: ${{ secrets.FIREBASE_APP_DISTRIBUTION_SERVICE_ACCOUNT_JSON_BASE64 }}
        run: |
          echo -n "$FIREBASE_APP_DISTRIBUTION_SERVICE_ACCOUNT_JSON_BASE64" | base64 --decode > ${{ runner.temp }}/firebase_app_distribution_service_account.json

      - name: Upload to Firebase App Distribution
        if: ${{ inputs.upload }}
        env:
          FIREBASE_APP_ID_ANDROID: ${{ secrets.FIREBASE_APP_ID_ANDROID }}
        run: |
          GOOGLE_APPLICATION_CREDENTIALS=${{ runner.temp }}/firebase_app_distribution_service_account.json firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk --app $FIREBASE_APP_ID_ANDROID --testers "yorifuji@gmail.com"

      - name: Clean up
        if: ${{ always() }}
        run: |
          rm -f ./android/key.properties

  ios:
    runs-on: ${{ (vars.RUNS_ON_SELF_HOSTED == null && 'macos-15') || 'self-hosted' }}
    environment: staging
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Run pre-process script
        shell: bash
        env:
          PREPROCESS_SCRIPT_BASE64: ${{ secrets.PREPROCESS_SCRIPT_BASE64 }}
        run: |
          if [ -n "$PREPROCESS_SCRIPT_BASE64" ]; then
            echo "$PREPROCESS_SCRIPT_BASE64" | base64 --decode > ${{ runner.temp }}/pre-process.sh && bash ${{ runner.temp }}/pre-process.sh
          fi

      - uses: subosito/flutter-action@e938fdf56512cc96ef2f93601a5a40bde3801046 # v2.19.0
        id: flutter-action
        with:
          flutter-version: ${{ (vars.FLUTTER_VERSION != null && vars.FLUTTER_VERSION) || '' }}
          channel: stable
          cache: ${{ (vars.RUNS_ON_SELF_HOSTED == null && true) || false }}
          architecture: arm64

      - run: flutter pub get

      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: |
            ios/Pods
            build/ios/pod_inputs.fingerprint
          key: cocoapods-cache-${{ runner.os }}-${{ runner.arch }}-${{ steps.flutter-action.outputs.VERSION }}-${{ hashFiles('ios/Podfile.lock', 'ios/Runner.xcodeproj/project.pbxproj') }}

      - name: flutterfire configure
        env:
          FIREBASE_SERVICE_ACCOUNT_JSON_BASE64: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON_BASE64 }}
        run: |
          which firebase || curl -sL https://firebase.tools | analytics=false bash
          firebase --version
          which flutterfire || dart pub global activate flutterfire_cli
          flutterfire -v
          echo -n "$FIREBASE_SERVICE_ACCOUNT_JSON_BASE64" | base64 --decode > ${{ runner.temp }}/firebase_service_account.json
          GOOGLE_APPLICATION_CREDENTIALS=${{ runner.temp }}/firebase_service_account.json make flutterfire-configure-stg

      - name: Extract App Store Connect API Private Key
        env:
          APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
          APPLE_API_AUTHKEY_P8_BASE64: ${{ secrets.APPLE_API_AUTHKEY_P8_BASE64 }}
        run: |
          mkdir -p ./private_keys
          echo -n "$APPLE_API_AUTHKEY_P8_BASE64" | base64 --decode > ./private_keys/AuthKey_$APPLE_API_KEY_ID.p8

      - name: Create ExportOptions.plist and Runner.entitlements
        env:
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: |
          cat << EOS > ./ios/ExportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>compileBitcode</key>
            <false/>
            <key>manageAppVersionAndBuildNumber</key>
            <false/>
            <key>method</key>
            <string>release-testing</string>
            <key>teamID</key>
            <string>${APPLE_TEAM_ID}</string>
          </dict>
          </plist>
          EOS

      - name: Build
        env:
          APPLE_API_ISSUER_ID: ${{ secrets.APPLE_API_ISSUER_ID }}
          APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
        run: |
          flutter build ios \
            --config-only \
            --no-codesign \
            --dart-define=FLAVOR=stg
          xcodebuild archive \
            CODE_SIGNING_ALLOWED=NO \
            -archivePath ./build/ios/Runner.xcarchive \
            -workspace ./ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -destination "generic/platform=iOS" | xcbeautify
          codesign \
            --entitlements ios/Runner/Runner.entitlements \
            --force \
            --sign "-" build/ios/Runner.xcarchive/Products/Applications/Runner.app
          xcodebuild -exportArchive \
            -archivePath ./build/ios/Runner.xcarchive \
            -exportPath ./build/ios/ipa \
            -exportOptionsPlist ./ios/ExportOptions.plist \
            -allowProvisioningUpdates \
            -authenticationKeyIssuerID $APPLE_API_ISSUER_ID \
            -authenticationKeyID $APPLE_API_KEY_ID \
            -authenticationKeyPath `pwd`/private_keys/AuthKey_$APPLE_API_KEY_ID.p8 | xcbeautify

      - name: find xcarchive
        run: find ./build/ios/Runner.xcarchive

      - name: upload dSYM
        run: |
          echo $GITHUB_WORKSPACE
          find "${GITHUB_WORKSPACE}/build/ios/Runner.xcarchive/dSYMs/Runner.app.dSYM"
          ./ios/Pods/FirebaseCrashlytics/upload-symbols \
            -d \
            -gsp "${GITHUB_WORKSPACE}/ios/Runner/GoogleService-Info.plist" \
            -p ios \
            -b "${GITHUB_WORKSPACE}/build/ios/Runner.xcarchive/dSYMs/Runner.app.dSYM"

      - name: Find ipa file path
        id: info
        run: |
          echo "app-path=$(pwd)/$(find build/ios/ipa -type f -name '*.ipa')" >> $GITHUB_OUTPUT

      - name: Extract Firebase App Distribution Service Account file
        if: ${{ inputs.upload }}
        env:
          FIREBASE_APP_DISTRIBUTION_SERVICE_ACCOUNT_JSON_BASE64: ${{ secrets.FIREBASE_APP_DISTRIBUTION_SERVICE_ACCOUNT_JSON_BASE64 }}
        run: |
          echo -n "$FIREBASE_APP_DISTRIBUTION_SERVICE_ACCOUNT_JSON_BASE64" | base64 --decode > ${{ runner.temp }}/firebase_app_distribution_service_account.json

      - name: Upload to Firebase App Distribution
        if: ${{ inputs.upload }}
        env:
          FIREBASE_APP_ID_IOS: ${{ secrets.FIREBASE_APP_ID_IOS }}
          APP_PATH: ${{ steps.info.outputs.app-path }}
        run: |
          GOOGLE_APPLICATION_CREDENTIALS=${{ runner.temp }}/firebase_app_distribution_service_account.json firebase appdistribution:distribute $APP_PATH --app $FIREBASE_APP_ID_IOS --testers "yorifuji@gmail.com"

      - name: Clean up
        if: ${{ always() }}
        run: |
          rm -rf ~/Library/MobileDevice/Provisioning\ Profiles
          rm -rf ./private_keys

  # macos:
  #   runs-on: ${{ (vars.RUNS_ON_SELF_HOSTED == null && 'macos-15') || 'self-hosted' }}
  #   environment: staging
  #   timeout-minutes: 30
  #   steps:
  #     - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

  #     - name: Run pre-process script
  #       shell: bash
  #       env:
  #         PREPROCESS_SCRIPT_BASE64: ${{ secrets.PREPROCESS_SCRIPT_BASE64 }}
  #       run: |
  #         if [ -n "$PREPROCESS_SCRIPT_BASE64" ]; then
  #           echo "$PREPROCESS_SCRIPT_BASE64" | base64 --decode > ${{ runner.temp }}/pre-process.sh && bash ${{ runner.temp }}/pre-process.sh
  #         fi

  #     - uses: subosito/flutter-action@e938fdf56512cc96ef2f93601a5a40bde3801046 # v2.19.0
  #       with:
  #         flutter-version: ${{ (vars.FLUTTER_VERSION != null && vars.FLUTTER_VERSION) || '' }}
  #         channel: stable
  #         cache: ${{ (vars.RUNS_ON_SELF_HOSTED == null && true) || false }}
  #         architecture: arm64

  #     - run: flutter pub get

  #     - name: flutterfire configure
  #       env:
  #         FIREBASE_SERVICE_ACCOUNT_JSON_BASE64: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON_BASE64 }}
  #       run: |
  #         which firebase || curl -sL https://firebase.tools | analytics=false bash
  #         dart pub global activate flutterfire_cli && flutterfire -v
  #         echo -n "$FIREBASE_SERVICE_ACCOUNT_JSON_BASE64" | base64 --decode > ${{ runner.temp }}/firebase_service_account.json
  #         GOOGLE_APPLICATION_CREDENTIALS=${{ runner.temp }}/firebase_service_account.json make flutterfire-configure-stg

  #     - run: flutter build macos --dart-define=FLAVOR=stg

  #     - if: ${{ inputs.upload }}
  #       run: |
  #         pushd build/macos/Build/Products/Release
  #         zip -r buzz_recipe_viewer_macos_stg.zip buzz_recipe_viewer.app
  #         popd
  #         mv build/macos/Build/Products/Release/buzz_recipe_viewer_macos_stg.zip ./

  #     - uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
  #       if: ${{ inputs.upload }}
  #       with:
  #         path: buzz_recipe_viewer_macos_stg.zip
  #         name: buzz_recipe_viewer_macos_stg
  #         overwrite: true

  action-timeline:
    needs: [android, ios]
    if: ${{ !cancelled() && github.event.workflow == '.github/workflows/deliver-stg.yml' }}
    timeout-minutes: 30
    runs-on: ubuntu-24.04
    permissions: {}
    steps:
      - uses: Kesin11/actions-timeline@427ee2cf860166e404d0d69b4f2b24012bb7af4f # v2.2.3
