name: deliver when tagged

on:
  push:
    tags:
      - v*
  workflow_dispatch:

permissions:
  contents: read

jobs:
  android:
    uses: ./.github/workflows/deliver-android.yml
    secrets: inherit

  ios:
    uses: ./.github/workflows/deliver-ios.yml
    secrets: inherit
