name: Deliver on tagged

run-name: Deliver on Tagged ${{ (vars.RUNS_ON_SELF_HOSTED == null && '(on GitHub-hosted)') || '(on self-hosted)' }}

on:
  push:
    tags:
      - v*
  workflow_dispatch:

permissions:
  contents: read

jobs:
  prod:
    uses: ./.github/workflows/deliver-prod.yml
    secrets: inherit

  stg:
    uses: ./.github/workflows/deliver-stg.yml
    secrets: inherit

  pages:
    uses: ./.github/workflows/deliver-pages.yml
    secrets: inherit
    permissions:
      contents: read
      pages: write
      id-token: write

  action-timeline:
    needs: [prod, stg, pages]
    if: ${{ !cancelled() }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: Kesin11/actions-timeline@v2
