name: job deliver-android

on:
  workflow_call:

jobs:
  deliver-android:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Create .env
        shell: bash
        run: |
          touch .env
          echo "APPLICATION_ID=${{ secrets.APPLICATION_ID }}" >> .env
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Run flutter version
        run: flutter --version

      - name: Run flutter pub get
        run: flutter pub get

      - run: flutter build apk

      - run: flutter build appbundle

      - name: Notify Slack
        uses: 8398a7/action-slack@v3.8.0
        with:
          status: ${{ job.status }}
          author_name: "deliver-android"
          fields: repo,message,commit,author,action,eventName,ref,workflow,pullRequest
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
        if: always()
