name: job deliver-ios

on:
  workflow_call:

env:
  IOS_IPA_PATH: 'build/ios/ipa/buzz_recipe_viewer.ipa'

jobs:
  deliver-ios:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create .env
        shell: bash
        run: |
          touch .env
          echo "ALGOLIA_APPLICATION_ID=${{ secrets.ALGOLIA_APPLICATION_ID }}" >> .env
          echo "ALGOLIA_API_KEY=${{ secrets.ALGOLIA_API_KEY }}" >> .env

      - name: Import Provisioning Profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo -n ${{ secrets.APPLE_PROVISIONING_PROFILE }} | base64 -d > ~/Library/MobileDevice/Provisioning\ Profiles/distribution.mobileprovision

      - name: Import Distribution Certificates
        uses: Apple-Actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.APPLE_CERTIFICATES_P12 }}
          p12-password: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Run flutter version
        run: flutter --version

      - name: Run flutter pub get
        run: flutter pub get

      - name: Build ipa
        run: flutter build ipa --export-options-plist=./ios/ExportOptions.plist

      - name: Upload to App Store Connect
        run: xcrun altool --upload-app --type ios -f $IOS_IPA_PATH -u "${{ secrets.APPLE_APPLE_ID }}" -p "${{ secrets.APPLE_APP_PASS }}"

      - name: Notify Slack
        uses: 8398a7/action-slack@v3.8.0
        with:
          status: ${{ job.status }}
          author_name: 'deliver-ios'
          fields: repo,message,commit,author,action,eventName,ref,workflow,pullRequest
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
        if: always()
