name: Deliver for GitHub Pages on push

run-name: Deliver for GitHub Pages on push ${{ (vars.RUNS_ON_SELF_HOSTED == null && '(on GitHub-hosted)') || '(on self-hosted)' }}

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash -euo pipefail {0}

jobs:
  check:
    uses: ./.github/workflows/check.yml
    permissions:
      contents: read
      pull-requests: write
      checks: write
    secrets: inherit

  pages:
    needs: check
    uses: ./.github/workflows/deliver-dev.yml
    secrets: inherit
    permissions:
      contents: read
      pages: write
      id-token: write

  action-timeline:
    needs: pages
    if: ${{ !cancelled() }}
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    permissions: {}
    steps:
      - uses: Kesin11/actions-timeline@427ee2cf860166e404d0d69b4f2b24012bb7af4f # v2.2.3
