name: deliver on tagged

run-name: Deliver on Tagged ${{ (vars.RUNS_ON_SELF_HOSTED == null && '(on GitHub-hosted)') || '(on self-hosted)' }}

on:
  push:
    tags:
      - v*

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prod:
    uses: ./.github/workflows/deliver-prod.yml
    secrets: inherit

  stg:
    uses: ./.github/workflows/deliver-stg.yml
    secrets: inherit
