name: deliver

on:
  push:
    tags:
      - v*
  workflow_dispatch:

permissions:
  contents: read

jobs:
  android:
    uses: ./.github/workflows/build-android.yml
    secrets: inherit
    with:
      upload-artifact: true

  google-play:
    needs: android
    uses: ./.github/workflows/upload-android.yml
    secrets: inherit
    with:
      filename: ${{ needs.android.outputs.filename }}
      release-name: ${{ needs.android.outputs.release-name }}
      package-name: ${{ needs.android.outputs.package-name }}

  ios:
    uses: ./.github/workflows/build-ios.yml
    secrets: inherit
    with:
      upload-artifact: true

  app-store:
    needs: ios
    uses: ./.github/workflows/upload-ios.yml
    secrets: inherit
    with:
      filename: ${{ needs.ios.outputs.filename }}
