name: 02-b deliver for production

on:
  push:
    tags:
      - v*
  workflow_dispatch:

permissions:
  contents: read

jobs:
  android:
    uses: ./.github/workflows/deliver-prod-android.yml
    secrets: inherit

  ios:
    uses: ./.github/workflows/deliver-prod-ios.yml
    secrets: inherit
