name: Dependency Update Checker

run-name: Dependency Update Checker ${{ (vars.RUNS_ON_SELF_HOSTED == null && '(on GitHub-hosted)') || '(on self-hosted)' }}

on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * 0'

env:
  GIT_USER_EMAIL: '41898282+github-actions[bot]@users.noreply.github.com'
  GIT_USER_NAME: 'github-actions[bot]'

defaults:
  run:
    shell: bash -euo pipefail {0}

jobs:
  dependency-update-checker:
    runs-on: ${{ (vars.RUNS_ON_SELF_HOSTED == null && 'macos-latest') || 'self-hosted' }}
    timeout-minutes: 30
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - run: |
          git config --local user.name $GIT_USER_NAME
          git config --local user.email $GIT_USER_EMAIL

      - uses: actions/create-github-app-token@21cfef2b496dd8ef5b904c159339626a10ad380e # v1.11.6
        id: app-token
        with:
          app-id: ${{ secrets.APPS_APP_ID }}
          private-key: ${{ secrets.APPS_PRIVATE_KEY }}

      - uses: subosito/flutter-action@f2c4f6686ca8e8d6e6d0f28410eeef506ed66aff # v2.18.0
        with:
          flutter-version: ${{ (vars.FLUTTER_VERSION != null && vars.FLUTTER_VERSION) || '' }}
          channel: stable
          cache: ${{ (vars.RUNS_ON_SELF_HOSTED == null && true) || false }}

      - run: flutter precache --ios --macos

      - run: rm pubspec.lock ios/Podfile.lock macos/Podfile.lock

      - run: flutter pub get

      - run: cd ios && pod repo update && pod install --repo-update

      - run: cd macos && pod repo update && pod install --repo-update

      - run: git diff

      - name: Create PR if changes
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "Update dependencies"
            git checkout -b ci/dependency-update-checker
            git push -f origin ci/dependency-update-checker
            gh pr create --base ${{ github.ref_name }} --head ci/dependency-update-checker --title "CI: Update dependencies" --body "Update dependencies" || exit 0
          else
            git push -d origin ci/dependency-update-checker || exit 0
          fi
