name: Dependency Update Checker

run-name: Dependency Update Checker ${{ (vars.RUNS_ON_SELF_HOSTED == null && '(on GitHub-hosted)') || '(on self-hosted)' }}

on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * 0'

env:
  GIT_USER_EMAIL: '41898282+github-actions[bot]@users.noreply.github.com'
  GIT_USER_NAME: 'github-actions[bot]'

permissions:
  contents: write
  pull-requests: write

jobs:
  dependency-update-checker:
    runs-on: ${{ (vars.RUNS_ON_SELF_HOSTED == null && 'macos-latest') || 'self-hosted' }}
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - run: |
          git config --local user.name $GIT_USER_NAME
          git config --local user.email $GIT_USER_EMAIL

      - uses: actions/create-github-app-token@5d869da34e18e7287c1daad50e0b8ea0f506ce69 # v1.11.0
        id: app-token
        with:
          app-id: ${{ secrets.APPS_APP_ID }}
          private-key: ${{ secrets.APPS_PRIVATE_KEY }}

      - uses: subosito/flutter-action@44ac965b96f18d999802d4b807e3256d5a3f9fa1 # v2.16.0
        with:
          flutter-version: ${{ (vars.FLUTTER_VERSION != null && vars.FLUTTER_VERSION) || '' }}
          channel: stable
          cache: ${{ (vars.RUNS_ON_SELF_HOSTED == null && true) || false }}

      - run: flutter precache --ios --macos

      - run: rm pubspec.lock ios/Podfile.lock macos/Podfile.lock

      - run: flutter pub get

      - run: cd ios && pod repo update && pod install --repo-update

      - run: cd macos && pod repo update && pod install --repo-update

      - run: git diff

      - name: Create PR if changes
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "Update dependencies"
            git checkout -b ci/dependency-update-checker
            git push -f origin ci/dependency-update-checker
            gh pr create --base ${{ github.ref_name }} --head ci/dependency-update-checker --title "CI: Update dependencies" --body "Update dependencies" || exit 0
          else
            git push -d origin ci/dependency-update-checker || exit 0
          fi
