name: Workflow for main

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  analyze:
    uses: ./.github/workflows/analyze.job.yaml
    secrets: inherit
  test:
    uses: ./.github/workflows/test.job.yaml
    secrets: inherit
