name: workflow for main branch

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  analyze-job:
    uses: ./.github/workflows/analyze.job.yaml
    secrets: inherit
  test-job:
    uses: ./.github/workflows/test.job.yaml
    secrets: inherit
