name: Nightly build

run-name: Nightly Build ${{ (vars.RUNS_ON_SELF_HOSTED == null && '(on GitHub-hosted)') || '(on self-hosted)' }}

on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * *'

jobs:
  check:
    uses: ./.github/workflows/check.yml
    permissions:
      contents: read
      pull-requests: write
      checks: write
    secrets: inherit

  build-prod:
    needs: check
    uses: ./.github/workflows/deliver-prod.yml
    permissions:
      contents: read
    secrets: inherit
    with:
      upload: false

  build-stg:
    needs: check
    uses: ./.github/workflows/deliver-stg.yml
    permissions:
      contents: read
    secrets: inherit
    with:
      upload: false

  build-dev:
    needs: check
    uses: ./.github/workflows/deliver-dev.yml
    secrets: inherit
    permissions:
      contents: read
      pages: write
      id-token: write
    with:
      upload: false

  action-timeline:
    needs: [check, build-prod, build-stg, build-dev]
    if: ${{ !cancelled() }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: Kesin11/actions-timeline@3046833d9aacfd7745c5264b7f3af851c3e2a619 # v2.2.1
