name: Assign PR to author

on:
  pull_request:
    types: opened

jobs:
  pr-assign:
    runs-on: ${{ (vars.RUNS_ON_SELF_HOSTED == null && 'ubuntu-latest') || 'self-hosted' }}
    permissions:
      contents: read
      pull-requests: write
      repository-projects: read
    if: ${{ !contains(github.actor, '[bot]') }}
    timeout-minutes: 30
    steps:
      - env:
          GH_TOKEN: ${{ github.token }}
        run: gh pr edit ${{ github.event.number }} --add-assignee ${{ github.actor }} --repo ${{ github.repository }}
