name: Assign PR to author

run-name: Assign PR Author ${{ (vars.RUNS_ON_SELF_HOSTED == null && '(on GitHub-hosted)') || '(on self-hosted)' }}

on:
  pull_request:
    types: opened

defaults:
  run:
    shell: bash -euo pipefail {0}

jobs:
  pr-assign:
    if: ${{ !contains(github.actor, '[bot]') }}
    runs-on: ${{ (vars.RUNS_ON_SELF_HOSTED == null && 'ubuntu-24.04') || 'self-hosted' }}
    permissions:
      contents: read
      pull-requests: write
      repository-projects: read
    timeout-minutes: 30
    steps:
      - uses: actions/create-github-app-token@af35edadc00be37caa72ed9f3e6d5f7801bfdf09 # v1.11.7
        id: app-token
        with:
          app-id: ${{ secrets.APPS_APP_ID }}
          private-key: ${{ secrets.APPS_PRIVATE_KEY }}

      - env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: >
          gh pr edit ${{ github.event.number }}
          --add-assignee ${{ github.actor }}
          --repo ${{ github.repository }}
