name: PR Labeler

run-name: PR Labeler ${{ (vars.RUNS_ON_SELF_HOSTED == null && '(on GitHub-hosted)') || '(on self-hosted)' }}

on:
  pull_request:
    types: opened

jobs:
  pr-labeler:
    runs-on: ${{ (vars.RUNS_ON_SELF_HOSTED == null && 'ubuntu-latest') || 'self-hosted' }}
    permissions:
      contents: read
      pull-requests: write
    timeout-minutes: 30
    steps:
      - id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APPS_APP_ID }}
          private-key: ${{ secrets.APPS_PRIVATE_KEY }}

      - uses: TimonVS/pr-labeler-action@v5
        with:
          repo-token: ${{ steps.app-token.outputs.token }}
