name: Dependency Update Checker

run-name: Dependency Update Checker ${{ (vars.RUNS_ON_SELF_HOSTED == null && '(on GitHub-hosted)') || '(on self-hosted)' }}

on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * 0'

env:
  GIT_USER_EMAIL: '41898282+github-actions[bot]@users.noreply.github.com'
  GIT_USER_NAME: 'github-actions[bot]'

permissions:
  contents: write
  pull-requests: write

jobs:
  dependency-update-checker:
    runs-on: ${{ (vars.RUNS_ON_SELF_HOSTED == null && 'ubuntu-latest') || 'self-hosted' }}
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ (vars.FLUTTER_VERSION != null && vars.FLUTTER_VERSION) || '' }}
          channel: stable
          cache: ${{ (vars.RUNS_ON_SELF_HOSTED == null && true) || false }}

      - run: |
          rm pubspec.lock
          rm ios/Podfile.lock macos/Podfile.lock
      - run: flutter pub get
      - run: sudo gem install cocoapods
      - run: cd ios && pod repo update && pod install --repo-update
      - run: cd macos && pod repo update && pod install --repo-update
      - run: git diff

      - name: Create PR if changes
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config --local user.name $GIT_USER_NAME
            git config --local user.email $GIT_USER_EMAIL
            git add .
            git commit -m "Update dependencies"
            git checkout -b ci/dependency-update-checker
            git push -f origin ci/dependency-update-checker
            gh pr create --base ${{ github.ref_name }} --head ci/dependency-update-checker --title "CI: Update dependencies" --body "Update dependencies" || exit 0
          else
            git push -d origin ci/dependency-update-checker || exit 0
          fi
