name: scheduled nightly build

run-name: Nightly Build ${{ (vars.RUNS_ON_SELF_HOSTED == null && '(on GitHub-hosted)') || '(on self-hosted)' }}

on:
  workflow_dispatch:
  schedule:
    - cron: "0 15 * * *"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    uses: ./.github/workflows/check.yml
    permissions:
      contents: read
      issues: write
      pull-requests: write
    secrets: inherit

  build:
    needs: check
    uses: ./.github/workflows/deliver-prod.yml
    secrets: inherit
    with:
      upload: false
