name: Scheduled nightly build

run-name: Nightly Build ${{ (vars.RUNS_ON_SELF_HOSTED == null && '(on GitHub-hosted)') || '(on self-hosted)' }}

on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * *'

permissions:
  contents: read

jobs:
  check:
    uses: ./.github/workflows/check.yml
    permissions:
      contents: read
      pull-requests: write
      checks: write
    secrets: inherit

  build-prod:
    needs: check
    uses: ./.github/workflows/deliver-prod.yml
    secrets: inherit
    with:
      upload: false

  build-stg:
    needs: check
    uses: ./.github/workflows/deliver-stg.yml
    secrets: inherit
    with:
      upload: false

  build-pages:
    needs: check
    uses: ./.github/workflows/deliver-pages.yml
    secrets: inherit
    permissions:
      contents: read
      pages: write
      id-token: write
    with:
      upload: false

  action-timeline:
    needs: [check, build-prod, build-stg, build-pages]
    if: ${{ !cancelled() }}
    runs-on: ubuntu-latest
    steps:
      - uses: Kesin11/actions-timeline@v2
