name: scheduled nightly build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * *'

permissions:
  contents: read

jobs:
  android:
    uses: ./.github/workflows/build-android.yml
    secrets: inherit
    with:
      upload-artifact: false

  ios:
    uses: ./.github/workflows/build-ios.yml
    secrets: inherit
    with:
      code-sign-style: auto
      upload-artifact: false
