name: Tagging on merged

run-name: Tagging on Merged ${{ (vars.RUNS_ON_SELF_HOSTED == null && '(on GitHub-hosted)') || '(on self-hosted)' }}

on:
  pull_request:
    branches:
      - main
    types: [closed]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  tagged:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'releases/')
    runs-on: ${{ (vars.RUNS_ON_SELF_HOSTED == null && 'ubuntu-latest') || 'self-hosted' }}
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: get version from pubspec.yaml
        run: echo "BUMP_VERSION=$(yq '.version' pubspec.yaml)" >> $GITHUB_ENV

      - id: app-token
        uses: actions/create-github-app-token@31c86eb3b33c9b601a1f60f98dcbfd1d70f379b4 # v1.10.3
        with:
          app-id: ${{ secrets.APPS_APP_ID }}
          private-key: ${{ secrets.APPS_PRIVATE_KEY }}

      - name: create tag and release note
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: gh release create v$BUMP_VERSION --generate-notes --draft
