name: Tagging on merged

run-name: Tagging on Merged ${{ (vars.RUNS_ON_SELF_HOSTED == null && '(on GitHub-hosted)') || '(on self-hosted)' }}

on:
  pull_request:
    branches:
      - main
    types: [closed]
  workflow_dispatch:

defaults:
  run:
    shell: bash -euo pipefail {0}

jobs:
  tagged:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'releases/')
    runs-on: ${{ (vars.RUNS_ON_SELF_HOSTED == null && 'ubuntu-24.04') || 'self-hosted' }}
    timeout-minutes: 30
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: get version from pubspec.yaml
        run: echo "BUMP_VERSION=$(yq '.version' pubspec.yaml)" >> $GITHUB_ENV

      - id: app-token
        uses: actions/create-github-app-token@af35edadc00be37caa72ed9f3e6d5f7801bfdf09 # v1.11.7
        with:
          app-id: ${{ secrets.APPS_APP_ID }}
          private-key: ${{ secrets.APPS_PRIVATE_KEY }}

      - name: create tag and release note
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: gh release create v$BUMP_VERSION --generate-notes --draft
