name: upload android

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      filename:
        description: 'aab filename to download from artifact'
        required: true
        type: string
      release-name:
        description: 'release name'
        required: true
        type: string
      package-name:
        description: 'package name'
        required: true
        type: string

permissions:
  contents: read

jobs:
  upload:
    runs-on: macos-12
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: aab

      - name: Create google service account file
        env:
          GOOGLE_SERVICE_ACCOUNT_KEY_JSON_BASE64: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY_JSON_BASE64 }}
        run: |
          echo $GOOGLE_SERVICE_ACCOUNT_KEY_JSON_BASE64 | base64 --decode > android/service-account.json

      - name: Upload to Google Play
        uses: r0adkll/upload-google-play@78c9e796b1035c94169c101d8e46cb880194bfc3
        with:
          releaseFiles: ${{ inputs.filename }}
          serviceAccountJson: android/service-account.json
          packageName: ${{ inputs.package-name }}
          releaseName: ${{ inputs.release-name }}
          track: production
          status: completed
